version: '3.4'

services:
  c19_website:
    container_name: c19_website
    image: c19_website
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: c19_mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db